### ISSUE TITLE
Unable to run cucumber tests in parallel

### ISSUE THREAD

**Issue by alukash** [reportportal/agent-java-cucumber4#41] opened 2020-04-08 13:01 UTC
I get the below error when try to run cucumber tests in parallel (using maven-surefire-plugin):
"Attempting re-set scenario ID for unfinished scenario."

Note, if run tests in 1 thread then they work fine.

**Cucumber runner class:**
```
@RunWith(Cucumber.class)
@CucumberOptions(
		glue = { "io.magentys.cinnamon","uk.co.ee.myee.automation" }, 
		features = { "src/test/resources/features" },
		plugin = { "pretty", "com.epam.reportportal.cucumber.StepReporter", "json:target/cucumber-reports/cucumber.json" }) 
public class AllTests {
}
```

**Versions:**
- Report Portal:  EPAM supported instance of ReportPortal - https://rp.epam.com/ui/
- agent-java-cucumber4:  4.1.1
- cucumber-java:  4.2.6

**Attachments:**
- [pom.txt](https://github.com/reportportal/agent-java-cucumber/files/4450456/pom.txt)

**Comment by alukash** [comment] 2020-04-13 11:25
The issue does not occur in https://beta.demo.reportportal.io/ui/#login (RP v.5.0)

**Comment by evgenytkachenko** [comment] 2020-04-14 13:27
@alukash does it work when you use ScenarioReporter ?

**Comment by alukash** [comment] 2020-04-14 15:37
ScenarioReporter or StepReporter - does not matter - result is the same

**Comment by jurteg** [comment] 2020-05-18 21:40
Hey,
the issue is still can be reproduced on 5 version of both RP and cucumber agent.
@DzmitryHumianiuk does somebody looking at this? If not I'd like to fix that.

**Comment by DzmitryHumianiuk** [comment] 2020-05-19 11:30
@jurteg i guess nobody at the moment,
so you are very welcome to send us pull request with the fix.

**Comment by evgenytkachenko** [comment] 2020-05-19 12:50
@jurteg I have no issues when I use ScenarioReporter and RP 5.1
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber4</artifactId>
            <version>5.0.0-BETA-9</version>
            <scope>test</scope>
        </dependency>

**Comment by jurteg** [comment] 2020-05-19 22:07
> 
> 
> @jurteg I have no issues when I use ScenarioReporter and RP 5.1
> 
> com.epam.reportportal
> agent-java-cucumber4
> 5.0.0-BETA-9
> test

@evgenytkachenko the issue does exist and I already found the cause so now preparing the fix.

**Comment by evgenytkachenko** [comment] 2020-05-19 22:53
@jurteg  As I mentioned I have no Issues with that and I used to have that issue with version 4 but with v5 it works just fine
Do you use StepReporter ?

**Comment by jurteg** [comment] 2020-05-19 23:05
@evgenytkachenko yes, I use the latest version of agent and RP server. But it doesn't matter, this issue was there from the very beginning, you just need proper tests to reveal that. Cucumber itself handles this easily, but the reporter not, cause it has to deal with parallelization. And most important - this can be only reproduced with scenario granularity level of parallelization.

**Comment by jurteg** [comment] 2020-05-19 23:07
@evgenytkachenko we have more than 1200 UI tests and about 200 features, so there are bunch of cases we can challenge cucumber agent against.

**Comment by jurteg** [comment] 2020-05-20 11:15
The pull request has been placed.

**Comment by evgenytkachenko** [comment] 2020-05-20 11:44
I see

**Comment by HardNorth** [comment] 2020-05-20 17:24
The fix was merged. I'm going to publish a client RC tomorrow, after that I'll build a new beta of the agent with the RC in dependencies.

**Comment by evgenytkachenko** [comment] 2020-05-20 17:27
Thanks @HardNorth 
What would be a timeline for a final version ?

**Comment by HardNorth** [comment] 2020-05-21 15:41
Here it is: https://bintray.com/epam/reportportal/agent-java-cucumber4/5.0.0-BETA-10

@evgenytkachenko It goes really slow, after TestNG I'm going to release JUnits and only then it is cucumbers' turn. So at least a month I would say.

**Comment by jurteg** [comment] 2020-06-09 11:41
I suppose the issue has been fixed?

**Comment by evgenytkachenko** [comment] 2020-06-09 17:06
I did not have any Issues with version 5 of the agent, so it still works fine for me when I run in parallel

**Comment by jurteg** [comment] 2020-06-11 10:40
@evgenytkachenko the issue only happens if the feature has several scenarios with the same name. This case has been fixed.
@alukash could you plesae check it now?

**Comment by alukash** [comment] 2020-06-11 11:22
> 
> 
> @evgenytkachenko the issue only happens if the feature has several scenarios with the same name. This case has been fixed.
> @alukash could you plesae check it now?

The original issue is for RPv4. I do not have the issue with v5(for the same test set).

**Comment by HardNorth** [comment] 2020-08-05 08:41
So, closed then

**Closed by HardNorth** 2020-08-05 08:41 UTC
Labels: bug
